apiVersion: v1
kind: Service
metadata:
  name: ordering-service
  namespace: default
spec:
  selector:
    app: ordering-system
  type: NodePort
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30080
      protocol: TCP

